version: '3.0'

services:
  db:
    image: postgres:15.1-alpine
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    networks:
      - aggregator
  app:
    image: aggregator
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - aggregator
    depends_on:
      - db
    stdin_open: true
    tty: true
# volumes:
#   pgdata:
networks:
  aggregator:
